import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import { ThemeContext } from "./context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className=" bg-white dark:bg-gray-900 text-black dark:text-white"
      >
        <ThemeContext>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </ThemeContext>
      </body>
    </html>
  );
}
